### ISSUE TITLE
Files are missing!

### ISSUE THREAD

**Issue by stautonico** [caiquecamargo/learning-rust#1]
**Describe the bug**
`git clone` results in an empty repository

**To Reproduce**
1. Type `git clone https://github.com/caiquecamargo/learning-rust`
2. cd into the cloned folder
3. ls to observe that all the files are missing

**Expected behavior**
The repository should be full of files

**Screenshots**
![2021-09-15-181443_5120x1440_scrot](https://user-images.githubusercontent.com/36276517/133517127-acebdf6d-6eed-423e-b117-0df3f9fba05c.png)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
- Kernel: 5.10.61

**Additional context**
This is a meme issue, I was just looking for resources to learn rust and I came across this repo

**Comment by caiquecamargo** [comment]
Full of files? One day who knows, I just created the repo

But whatever you find interesting out there and want to share, feel free.
